import Head from "next/head";
import PostsList from "@/components/Posts/PostsList";
import AddPostForm from "@/components/Posts/AddPostform";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <AddPostForm />
        <PostsList />
      </main>
    </>
  );
}
